name: RainManNG
main: me.abcric.bukkit.rainman.RainMan
version: 1.1
api-version: 1.18
authors: 
   - ABCRic
   - Velnias75
commands:
   rainman:
      description: This is the global plugin command.
      usage: /rainman <command>
permissions:
    rainman.admin:
        description: Allows the user to control the plugin