name: RainManNG
main: de.rangun.RainManNG.RainManNG
version: 1.1
api-version: 1.18
authors: 
   - ABCRic
   - Velnias75
commands:
   rainmanng:
      description: This is the global plugin command.
      usage: /rainmanng <command>
permissions:
    rainmanng.admin:
        description: Allows the user to control the plugin